name: dkgp-minimal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - numpy=1.21.6
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - matplotlib=3.5.3
  - seaborn=0.11.2
  - pip
  - pip:
    - gpytorch==1.9.1
    - pathlib
